CREATE TABLE accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    type          TEXT   NOT NULL CHECK (type IN ('CUSTOMER', 'MERCHANT', 'SYSTEM')),
    balance_minor BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT non_system_balance_not_negative CHECK (type = 'SYSTEM' OR balance_minor >= 0)
);

CREATE TABLE ledger_transactions (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payment_id UUID        NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- debit = negative, credit = positive
CREATE TABLE ledger_entries (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES ledger_transactions (id),
    account_id     BIGINT NOT NULL REFERENCES accounts (id),
    amount_minor   BIGINT NOT NULL CHECK (amount_minor <> 0)
);

CREATE INDEX ledger_entries_transaction_idx ON ledger_entries (transaction_id);
CREATE INDEX ledger_entries_account_idx ON ledger_entries (account_id);
