server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledgerflow}
    username: ${DB_USER:payment_user}
    password: ${DB_PASSWORD:payment_user}
  flyway:
    schemas: payments
    default-schema: payments
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
